### PR TITLE
avoid "too many open files" error when loading module info

### LINKED ISSUE #208: The latest version returns an error: too many open files
After updating to the latest version I get the following error:
`open <file-name>: too many open files`

I've got the following target in my Makefile:
```
LOCAL_PACKAGES="gitlab.com/cool-company/"
GO_FILES = $(shell find . -name "*.go" | grep -v vendor | uniq)

fmt: ## format code
	@gofumpt -l -w $(GO_FILES)
	@gci -w -l $(LOCAL_PACKAGES) $(GO_FILES)	
```

Interestingly enough `gci` doesn't have this problem

### PR DESCRIPTION
**Pull request by mvdan**
(see commit message)

Fixes #208.

### CODE REVIEW

**Comment by mvdan** [comment]
@screwyprof care to confirm that this fix works for you?

**Comment by mvdan** [comment]
note to self: add benchcmd benchmark numbers to the commit message before merging. I imagine we're slightly faster than before on average, due to the deduplication of `go mod edit -json` calls.

File: gofmt.go [hunk 1]
```diff
@@ -532,7 +528,49 @@ func gofmtMain(s *sequencer) {
...
 }
 
+type module struct {
+	Go     string
+	Module struct {
+		Path string
+	}
+}
+
+func loadModuleInfo(dir string) interface{} {
```
Comment (mdlayher) [inline gofmt.go:538]: any, or are you holding off on 1.18?

File: ulimit_unix_test.go [hunk 2]
```diff
@@ -0,0 +1,88 @@
+// Copyright (c) 2019, Daniel Martí <mvdan@mvdan.cc>
```
Comment (mdlayher) [inline ulimit_unix_test.go:1]: 2022?

File: ulimit_unix_test.go [hunk 3]
```diff
@@ -0,0 +1,88 @@
...
+)
+
+func init() {
+	// Here rather than in TestMain, to reuse the unix build tag.
+	if limit := os.Getenv("TEST_WITH_FILE_LIMIT"); limit != "" {
+		n, err := strconv.ParseUint(limit, 10, 64)
+		if err != nil {
+			panic(err)
+		}
+		rlimit := syscall.Rlimit{Cur: n, Max: n}
```
Comment (mdlayher) [inline ulimit_unix_test.go:29]: Generally you'll want x/sys/unix for weird syscalls because it'll get updates if things ever change on various UNIXes.

**Review by mdlayher — APPROVED** [review]

**Comment by screwyprof** [comment]
@mvdan I've tested it on my setup. Works just fine with `go version go1.17.8 darwin/amd64`

File: gofmt.go (hunk 1 above)
Comment (mvdan) [reply gofmt.go:538]: Yes :) I support two Go versions by default on most of my projects, including this one

File: ulimit_unix_test.go (hunk 2 above)
Comment (mvdan) [reply ulimit_unix_test.go:1]: I thought about it but I got lazy since it doesn't really matter. Then I went on to type these two sentences which is significantly more effort :wink: Fixed.

File: ulimit_unix_test.go (hunk 3 above)
Comment (mvdan) [reply ulimit_unix_test.go:29]: I considered this but guessed it was harmless given it's a test. I guess it's equally harmless to use x/sys/unix, and we already pull x/sys for other purposes. Done

**Comment by mvdan** [comment]
Thank you both! Merging on green. @screwyprof I'll release v0.3.1 sometime next week; you can use master until then if you wish.

**Comment by mvdan** [comment]
I had to redo part of the patch, because the old code was racy (multiple goroutines writing to globals) and didn't actually call `go mod edit -json` in each file's directory :see_no_evil: The tests will now catch these, and the bugs are fixed. Oops. These are three pretty nasty regressions in v0.3.0, meaning we should get a release out ASAP.

I'm less inclined to include benchmark numbers now, because master is racy, so it currently cheats by "caching" global values with module info, but in a racy way that's completely broken, so its performance is kinda random.

**Review by mdlayher — APPROVED** [review]
LGTM
